# -*- coding: utf-8 -*-
"""google_vision_ocr.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YiADzusHkfePjz72gslqNU45-G-R05lZ
"""

import os
from google.cloud import vision
from google.cloud.vision_v1 import types
from PIL import Image
import re

class OCRProcessor:
    def __init__(self, google_api_key_path):
        # Set up the Google Cloud Vision client
        os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = google_api_key_path
        self.client = vision.ImageAnnotatorClient()

    def extract_text_from_image(self, image_path):
        # Load the image
        with open(image_path, 'rb') as image_file:
            content = image_file.read()

        # Perform OCR using Google Cloud Vision
        image = types.Image(content=content)
        response = self.client.text_detection(image=image)
        texts = response.text_annotations

        # Extract the description (text) from the first annotation
        if texts:
            return texts[0].description
        return ""

    def clean_extracted_text(self, text):
        # Remove line feeds and join lines where necessary
        cleaned_text = " ".join(text.splitlines())
        return cleaned_text

# Example usage
if __name__ == "__main__":
    google_api_key_path = '/content/natural-venture-427916-q8-65fcaeac90b6.json'
    ocr_processor = OCRProcessor(google_api_key_path)
    image_path = "/content/gummibear.jpg"
    extracted_text = ocr_processor.extract_text_from_image(image_path)
    cleaned_text = ocr_processor.clean_extracted_text(extracted_text)

    print(cleaned_text)