# -*- coding: utf-8 -*-
"""main_pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SKNtMpUSoy49hCPmt-HSHA_KrapvbKRM
"""

pip install openai==0.28

!sudo apt update
!sudo apt install tesseract-ocr

!sudo apt install tesseract-ocr-deu

pip install faiss-cpu transformers  # Use faiss-gpu if you have a GPU

!pip install pytesseract

pip install pytesseract

from PIL import Image, ImageEnhance, ImageFilter
import pytesseract
import cv2
import numpy as np
from google.colab.patches import cv2_imshow

class OCRProcessor:

    def __init__(self):
        pass

    def preprocess_image(self, image_path):
        # Load the image using OpenCV
        image = cv2.imread(image_path, cv2.IMREAD_COLOR)

        # Convert to grayscale
        gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

        # Apply a binary threshold to get a binary image
        _, binary_image = cv2.threshold(gray, 150, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)

        # Remove noise
        denoised_image = cv2.medianBlur(binary_image, 3)

        # Apply dilation and erosion
        kernel = np.ones((1, 1), np.uint8)
        processed_image = cv2.dilate(denoised_image, kernel, iterations=1)
        processed_image = cv2.erode(processed_image, kernel, iterations=1)

        # Save the preprocessed image temporarily
        temp_filename = "temp_preprocessed_image.png"
        cv2.imwrite(temp_filename, processed_image)

        return temp_filename

    def extract_text_from_image(self, image_path, lang='deu'):
        # Preprocess the image
        preprocessed_image_path = self.preprocess_image(image_path)

        # Load the preprocessed image using Pillow
        image = Image.open(preprocessed_image_path)

        # Optionally, enhance contrast and sharpness
        enhancer = ImageEnhance.Contrast(image)
        image = enhancer.enhance(2)
        image = image.filter(ImageFilter.SHARPEN)

        # Use pytesseract to do OCR on the processed image
        text = pytesseract.image_to_string(image, lang=lang)

        return text

    def clean_extracted_text(self, text):
        # Remove line feeds and join lines where necessary
        cleaned_text = " ".join(text.splitlines())
        return cleaned_text

# import faiss
# import numpy as np
# import pandas as pd
# import torch
# from transformers import AutoTokenizer, AutoModel

# class ALDI_FAISS:
#     def __init__(self, df_description):
#         # Load sentence transformer model
#         self.model_name = "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
#         self.tokenizer = AutoTokenizer.from_pretrained(self.model_name)
#         self.model = AutoModel.from_pretrained(self.model_name)

#         self.df = df_description
#         self.index = None
#         self.build_index()

#     def encode_descriptions(self, descriptions):
#         """
#         Encode descriptions using the sentence transformer model.
#         """
#         # Tokenize descriptions
#         encoded_input = self.tokenizer(descriptions, padding=True, truncation=True, return_tensors="pt", max_length=128)
#         # Generate embeddings
#         with torch.no_grad():
#             model_output = self.model(**encoded_input)
#             embeddings = model_output.last_hidden_state.mean(dim=1)
#         return embeddings.numpy()

#     def build_index(self):
#         """
#         Build FAISS index from product descriptions.
#         """
#         descriptions = self.df['description'].tolist()
#         embeddings = self.encode_descriptions(descriptions)

#         # Creating the FAISS index (using L2 distance)
#         self.index = faiss.IndexFlatL2(embeddings.shape[1])
#         self.index.add(embeddings)  # Add embeddings to the index

#     def search(self, p_desc, k):
#         """
#         Search for top k products similar to a given product description.

#         :param p_desc: Product description string.
#         :param k: Number of similar products to return.
#         :return: DataFrame of the top k similar product descriptions.
#         """
#         query_embedding = self.encode_descriptions([p_desc])
#         distances, indices = self.index.search(query_embedding, k)
#         return self.df.iloc[indices[0]]  # Return DataFrame rows of the top k products

# # Example of using RAG
# if __name__ == "__main__":

#     df_description = pd.DataFrame({
#         'description': [
#             "A new coffee maker for espresso lovers",
#             "A new car toy for kids",
#             "Mirowave with all latest features",
#             "The best professional DSLR camera",
#             "Wireless headphones with noise cancellation",
#             "Waterproof smartwatch with long battery life",
#             "Must-Have Smartwatches & Fitness Trackers",
#             "Best Smartwatch for Health Monitoring",
#             "Best health tracker for everyone"
#         ]
#     })

#     product_index = ALDI_FAISS(df_description)
#     print ('input: ' +"Smartwatch with health tracking features\n")
#     similar_products = product_index.search("Smartwatch with health tracking features", 5)
#     print(similar_products)

#     print ('\n----------------------------------------------\n')

#     print ('input: ' +"Organic eggs 6 pack\n")

#     df_des_prod = pd.DataFrame({
#         'description': [
#             "Fresh organic strawberries 500g",
#             "Low-fat milk 1 liter",
#             "Whole wheat bread loaf",
#             "Pack of 12 free-range eggs"
#         ]
#     })

#     prod_index = ALDI_FAISS(df_des_prod)
#     # Example search query for a similar product
#     similar_products = prod_index.search("Organic eggs 6 pack", 2)
#     print(similar_products)

import faiss
import numpy as np
import pandas as pd
import torch
from transformers import AutoTokenizer, AutoModel
import openai

class ProductRAG:
    def __init__(self, df_description, openai_api_key):
        self.model_name = "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
        self.tokenizer = AutoTokenizer.from_pretrained(self.model_name)
        self.model = AutoModel.from_pretrained(self.model_name)
        self.df = df_description
        self.index = None
        self.openai_api_key = openai_api_key
        self.build_index()

    def encode_descriptions(self, descriptions):
        encoded_input = self.tokenizer(descriptions, padding=True, truncation=True, return_tensors="pt", max_length=128)
        with torch.no_grad():
            model_output = self.model(**encoded_input)
            embeddings = model_output.last_hidden_state.mean(dim=1)
        return embeddings.numpy()

    def build_index(self):
        descriptions = self.df['description'].tolist()
        embeddings = self.encode_descriptions(descriptions)
        self.index = faiss.IndexFlatL2(embeddings.shape[1])
        self.index.add(embeddings)

    def search(self, p_desc, k):
        query_embedding = self.encode_descriptions([p_desc])
        distances, indices = self.index.search(query_embedding, k)
        return self.df.iloc[indices[0]]

    def ask_question(self, input_description, k, question):
        similar_products = self.search(input_description, k)
        descriptions = similar_products['description'].tolist()
        context = f"Input product: {input_description}. Products for comparison with input product: " + ", ".join(descriptions)
        print ('\n----------------------------------------------\n')
        print ('context:: ', context)
        print ('\n----------------------------------------------\n')
        return self.generate_response(question, context)


    def generate_response(self, question, context):
        openai.api_key = self.openai_api_key
        prompt = f"Question: {question}\nContext: {context}\nAnswer:"
        response = openai.ChatCompletion.create(
            model='gpt-4o-2024-05-13',
            temperature=0,
            top_p=1,
            frequency_penalty=0,
            presence_penalty=0,
            messages=[{"role": "system", "content": "You are a helpful assistant."},
                      {"role": "user", "content": prompt}]
        )
        return response['choices'][0]['message']['content'].strip()

if __name__ == "__main__":



    # get this from user through UI
    image_path = "chocolate.jpg"

    # get this from user from UI
    comparative_question = 'check the nutritional labels of each product online and tell Which is healthier, the input or the similar products?'











    '''web scrapping for better context'''

    # DataFrame with descriptions of waffle products from Lidl, Netto, and potentially other products
    df_description = pd.DataFrame({
        'description': [
            "Lidl Belgian waffles 500g",
            "Netto maple syrup waffles 450g",
            "Lidl chocolate waffles 300g",
            "Netto classic waffles 500g",
            "Aldi blueberry waffles 400g"  # This is an existing product just for example completeness
        ]
    })




    '''OCR for input image'''

    ocr_processor = OCRProcessor()


    extracted_text = ocr_processor.extract_text_from_image(image_path, lang='deu')
    cleaned_text = ocr_processor.clean_extracted_text(extracted_text)
    # extracted text from image ( clean out the product description from here for FAISS)
    print ('\n----------------------------------------------\n')
    print('cleaned_text: '+cleaned_text)
    print ('\n----------------------------------------------\n')



    '''FAISS and RAG for comparsion'''

     # Initialize the ProductRAG instance with the DataFrame and your OpenAI API key
    product_rag = ProductRAG(df_description, 'sk-proj-KPmObpzz1tZO2uSsVLdMT3BlbkFJZeQ8Q9Ys5H8K5CRRdtzH')
    # Asking a comparative question about ALDI's waffles compared to similar products from Netto and Lidl

    # User input description for ALDI's waffles
    aldis_waffles_input = cleaned_text

    # Getting the answer by comparing the top 3 similar products
    answer = product_rag.ask_question(aldis_waffles_input, 3, comparative_question)

    # Print the answer provided by the RAG system
    print ('\n----------------------------------------------\n')
    print('Answer from bot:', answer)
    print ('\n----------------------------------------------\n')


    # return answer as response to UI
    # return answer

