# -*- coding: utf-8 -*-
"""ocr.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VuqQwDaG41dmVqnJ6V4JXbapvXd2vgjZ
"""

from PIL import Image, ImageEnhance, ImageFilter
import pytesseract
import cv2
import numpy as np

class OCRProcessor:
    def __init__(self, tesseract_cmd):
        self.tesseract_cmd = tesseract_cmd
        pytesseract.pytesseract.tesseract_cmd = tesseract_cmd

    def preprocess_image(self, image_path):
        # Load the image using OpenCV
        image = cv2.imread(image_path, cv2.IMREAD_COLOR)

        # Convert to grayscale
        gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

        # Apply a binary threshold to get a binary image
        _, binary_image = cv2.threshold(gray, 150, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)

        # Remove noise
        denoised_image = cv2.medianBlur(binary_image, 3)

        # Apply dilation and erosion
        kernel = np.ones((1, 1), np.uint8)
        processed_image = cv2.dilate(denoised_image, kernel, iterations=1)
        processed_image = cv2.erode(processed_image, kernel, iterations=1)

        # Save the preprocessed image temporarily
        temp_filename = "temp_preprocessed_image.png"
        cv2.imwrite(temp_filename, processed_image)

        return temp_filename

    def extract_text_from_image(self, image_path, lang='deu'):
        # Preprocess the image
        preprocessed_image_path = self.preprocess_image(image_path)

        # Load the preprocessed image using Pillow
        image = Image.open(preprocessed_image_path)

        # Optionally, enhance contrast and sharpness
        enhancer = ImageEnhance.Contrast(image)
        image = enhancer.enhance(2)
        image = image.filter(ImageFilter.SHARPEN)

        # Use pytesseract to do OCR on the processed image
        text = pytesseract.image_to_string(image, lang=lang)

        return text

    def clean_extracted_text(self, text):
        # Remove line feeds and join lines where necessary
        cleaned_text = " ".join(text.splitlines())
        return cleaned_text

# Example usage
if __name__ == "__main__":
    ocr_processor = OCRProcessor(tesseract_cmd=r'C:\Program Files\Tesseract-OCR\tesseract.exe')
    image_path = "chocolate.jpg"
    extracted_text = ocr_processor.extract_text_from_image(image_path, lang='deu')
    cleaned_text = ocr_processor.clean_extracted_text(extracted_text)
    print(cleaned_text)