# -*- coding: utf-8 -*-
"""prompts_template.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nXvUZ19XauJhbV5Kq04_NbJwn49ESw1d
"""

#promts
#scenario1: Scan Aldi Product
prompts1_1 = "What are the similar products from comepetitors with comprehensive ingredient and nutrient data?"
prompts1_2 = "What's the difference between Aldi Products and our competitor's similar products regarding ingredients and nutrients?"
prompts1_3 = "What certifications (gluten-free, vegan, fair trade) do the competitor's product have?"
prompts1_4 = "What would make our products more appealing compared to competitor's product?"
#scenario2: Scan Competitor Product
prompts2_1 = "What are the similar products from other comepetitors with comprehensive ingredient and nutrient data?"
prompts2_2 = "What's the difference between competitor's similar products regarding ingredients and nutrients?"
prompts2_3 = "What certifications (gluten-free, vegan, fair trade) do the competitor's product have?"
prompts2_4 = "What's the most similar product that Aldi have with comprehensive ingredient and nutrient data?"