# -*- coding: utf-8 -*-
"""prompts.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D_m3D4V50Sa55CpT4R0Q6EKKQZrBJn-s
"""

# #promts
# #scenario1: Scan Aldi Product
# prompts1_1 = "What are the similar products from comepetitors with comprehensive ingredient and nutrient data?"
# prompts1_2 = "What's the difference between Aldi Products and our competitor's similar products regarding ingredients and nutrients?"
# prompts1_3 = "What certifications (gluten-free, vegan, fair trade) do the competitor's product have?"
# prompts1_4 = "What would make our products more appealing compared to competitor's product?"
# #scenario2: Scan Competitor Product
# prompts2_1 = "What are the similar products from other comepetitors with comprehensive ingredient and nutrient data?"
# prompts2_2 = "What's the difference between competitor's similar products regarding ingredients and nutrients?"
# prompts2_3 = "What certifications (gluten-free, vegan, fair trade) do the competitor's product have?"
# prompts2_4 = "What's the most similar product that Aldi have with comprehensive ingredient and nutrient data?"

prompt1="Compare calorie amount of [input] and [similar products]. Answer in no more than 5 sentences, if you don't know the answer, just answer "I dont know"."
prompt2="Compare the price of [similar products].Answer in no more than 5 sentences, if you don't know the answer, just answer "I dont know"."
prompt3="Compare the amount of sugar of [input] and [similar products]. Answer in no more than 5 sentences, if you don't know the answer, just answer "I dont know"."
prompt4="Compare the allergens of [input] and [similar products]. Answer in no more than 5 sentences, if you don't know the answer, just answer "I dont know"."
prompt5="Compare the ingredients of [input] and [similar products]. What are [input] missing? Answer in no more than 5 sentences, if you don't know the answer, just answer "I dont know"."
prompt6="Give me an overview of the ingredients and nutrients of [similar products]. Answer in no more than 5 sentences, if you don't know the answer, just answer "I dont know"."

